.TH "/tmp/mktar.IsxLVL/brltty-4.4/Programs/ Directory Reference" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/tmp/mktar.IsxLVL/brltty-4.4/Programs/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbrlapi.h\fP"
.br
.PP

.RI "\fITypes, defines and functions prototypes for \fIBrlAPI's\fP library. \fP"
.ti -1c
.RI "file \fBbrlapi_constants.h\fP"
.br
.ti -1c
.RI "file \fBbrlapi_keycodes.h\fP"
.br
.ti -1c
.RI "file \fBbrlapi_protocol.h\fP"
.br
.PP

.RI "\fItypes and constants for \fIBrlAPI's\fP protocol \fP"
.in -1c
