.TH "brlapi_range_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_range_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbrlapi_keyCode_t\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBbrlapi_keyCode_t\fP \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type for raw keycode ranges
.PP
Denotes the set of keycodes between \fIfirst\fP and \fIlast\fP (inclusive) 
.SH "Field Documentation"
.PP 
.SS "\fBbrlapi_keyCode_t\fP \fBbrlapi_range_t::first\fP"first key of the range 
.SS "\fBbrlapi_keyCode_t\fP \fBbrlapi_range_t::last\fP"last key of the range 

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
