.TH "brlapi_writeStruct" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_writeStruct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdisplayNumber\fP"
.br
.ti -1c
.RI "unsigned int \fBregionBegin\fP"
.br
.ti -1c
.RI "unsigned int \fBregionSize\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBtextSize\fP"
.br
.ti -1c
.RI "unsigned char * \fBattrAnd\fP"
.br
.ti -1c
.RI "unsigned char * \fBattrOr\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "char * \fBcharset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBbrlapi_writeStruct\fP, replaced by \fBbrlapi_writeArguments_t\fP 
.SH "Field Documentation"
.PP 
.SS "unsigned char* \fBbrlapi_writeStruct::attrAnd\fP"
.SS "unsigned char* \fBbrlapi_writeStruct::attrOr\fP"
.SS "char* \fBbrlapi_writeStruct::charset\fP"
.SS "int \fBbrlapi_writeStruct::cursor\fP"
.SS "int \fBbrlapi_writeStruct::displayNumber\fP"
.SS "unsigned int \fBbrlapi_writeStruct::regionBegin\fP"
.SS "unsigned int \fBbrlapi_writeStruct::regionSize\fP"
.SS "char* \fBbrlapi_writeStruct::text\fP"
.SS "int \fBbrlapi_writeStruct::textSize\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
