.TH "BrlAPI handles" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrlAPI handles \- 
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBbrlapi_handle_t\fP \fBbrlapi_handle_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t BRLAPI_STDCALL \fBbrlapi_getHandleSize\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Each function provided by BrlAPI comes in two versions.
.PP
1. A version whose name is prefixed by brlapi_ for clients opening only one simultaneous connection with BrlAPI (most frequen case)
.PP
2. A version whose name is prefixed by brlapi__ for use by clients wishing to open more than one connection to BrlAPI.
.PP
A function called brlapi__foo is used in exactly the same way as its brlapi_foo counterpart, except that it takes an additional argument (the first one), which is a handle letting the client refer to a given connection in a similar manner to what file descriptors do.
.PP
In case you want to check that your code is not erroneously using brlapi_foo functions, define BRLAPI_NO_SINGLE_SESSION before including <\fBbrlapi.h\fP>: that will disable the declaration of all single session functions. 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBbrlapi_handle_t\fP \fBbrlapi_handle_t\fP"Type for BrlAPI hanles 
.SH "Function Documentation"
.PP 
.SS "size_t BRLAPI_STDCALL brlapi_getHandleSize (void)"Returns the size of an object of type brlapi_handle_t in bytes 
.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
