.TH "brlapi_header_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_header_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "\fBbrlapi_packetType_t\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of packets headers 
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBbrlapi_header_t::size\fP"
.SS "\fBbrlapi_packetType_t\fP \fBbrlapi_header_t::type\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
