.TH "brlapi_expandedKeyCode_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_expandedKeyCode_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBcommand\fP"
.br
.ti -1c
.RI "unsigned int \fBargument\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure holding the components of a key code as returned by \fBbrlapi_expandKeyCode()\fP 
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBbrlapi_expandedKeyCode_t::argument\fP"the argument value 
.SS "unsigned int \fBbrlapi_expandedKeyCode_t::command\fP"the command value 
.SS "unsigned int \fBbrlapi_expandedKeyCode_t::flags\fP"the flags value 
.SS "unsigned int \fBbrlapi_expandedKeyCode_t::type\fP"the type value 

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
