.TH "brlapi_describedKeyCode_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_describedKeyCode_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBcommand\fP"
.br
.ti -1c
.RI "unsigned int \fBargument\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "const char * \fBflag\fP [64-BRLAPI_KEY_FLAGS_SHIFT]"
.br
.ti -1c
.RI "\fBbrlapi_expandedKeyCode_t\fP \fBvalues\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure holding the components of a key code as returned by \fBbrlapi_describeKeyCode()\fP 
.SH "Field Documentation"
.PP 
.SS "unsigned int \fBbrlapi_describedKeyCode_t::argument\fP"the argument value 
.SS "const char* \fBbrlapi_describedKeyCode_t::command\fP"the command name 
.SS "const char* \fBbrlapi_describedKeyCode_t::flag\fP[64-BRLAPI_KEY_FLAGS_SHIFT]"the flag names 
.SS "unsigned int \fBbrlapi_describedKeyCode_t::flags\fP"the flag count 
.SS "const char* \fBbrlapi_describedKeyCode_t::type\fP"the type name 
.SS "\fBbrlapi_expandedKeyCode_t\fP \fBbrlapi_describedKeyCode_t::values\fP"the actual values of the components 

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
