.TH "brlapi_getDriverSpecificModePacket_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_getDriverSpecificModePacket_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmagic\fP"
.br
.ti -1c
.RI "unsigned char \fBnameLength\fP"
.br
.ti -1c
.RI "char \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of enterRawMode / suspend packets 
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBbrlapi_getDriverSpecificModePacket_t::magic\fP"
.SS "char \fBbrlapi_getDriverSpecificModePacket_t::name\fP"
.SS "unsigned char \fBbrlapi_getDriverSpecificModePacket_t::nameLength\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
