.TH "brlapi_error_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_error_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbrlerrno\fP"
.br
.ti -1c
.RI "int \fBlibcerrno\fP"
.br
.ti -1c
.RI "int \fBgaierrno\fP"
.br
.ti -1c
.RI "const char * \fBerrfun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
All information that is needed to describe brlapi errors 
.SH "Field Documentation"
.PP 
.SS "int \fBbrlapi_error_t::brlerrno\fP"
.SS "const char* \fBbrlapi_error_t::errfun\fP"
.SS "int \fBbrlapi_error_t::gaierrno\fP"
.SS "int \fBbrlapi_error_t::libcerrno\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
