.TH "brlapi_constants.h" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_constants.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.PP
.RI "\fB\fP"
.br
 
.PP
.in +1c
.in +1c
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NOOP\fP   (BRLAPI_KEY_CMD(0) + 0)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_LNUP\fP   (BRLAPI_KEY_CMD(0) + 1)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_LNDN\fP   (BRLAPI_KEY_CMD(0) + 2)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_WINUP\fP   (BRLAPI_KEY_CMD(0) + 3)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_WINDN\fP   (BRLAPI_KEY_CMD(0) + 4)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRDIFLN\fP   (BRLAPI_KEY_CMD(0) + 5)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXDIFLN\fP   (BRLAPI_KEY_CMD(0) + 6)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ATTRUP\fP   (BRLAPI_KEY_CMD(0) + 7)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ATTRDN\fP   (BRLAPI_KEY_CMD(0) + 8)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_TOP\fP   (BRLAPI_KEY_CMD(0) + 9)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_BOT\fP   (BRLAPI_KEY_CMD(0) + 10)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_TOP_LEFT\fP   (BRLAPI_KEY_CMD(0) + 11)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_BOT_LEFT\fP   (BRLAPI_KEY_CMD(0) + 12)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRPGRPH\fP   (BRLAPI_KEY_CMD(0) + 13)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXPGRPH\fP   (BRLAPI_KEY_CMD(0) + 14)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRPROMPT\fP   (BRLAPI_KEY_CMD(0) + 15)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXPROMPT\fP   (BRLAPI_KEY_CMD(0) + 16)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRSEARCH\fP   (BRLAPI_KEY_CMD(0) + 17)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXSEARCH\fP   (BRLAPI_KEY_CMD(0) + 18)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CHRLT\fP   (BRLAPI_KEY_CMD(0) + 19)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CHRRT\fP   (BRLAPI_KEY_CMD(0) + 20)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_HWINLT\fP   (BRLAPI_KEY_CMD(0) + 21)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_HWINRT\fP   (BRLAPI_KEY_CMD(0) + 22)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_FWINLT\fP   (BRLAPI_KEY_CMD(0) + 23)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_FWINRT\fP   (BRLAPI_KEY_CMD(0) + 24)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_FWINLTSKIP\fP   (BRLAPI_KEY_CMD(0) + 25)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_FWINRTSKIP\fP   (BRLAPI_KEY_CMD(0) + 26)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_LNBEG\fP   (BRLAPI_KEY_CMD(0) + 27)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_LNEND\fP   (BRLAPI_KEY_CMD(0) + 28)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_HOME\fP   (BRLAPI_KEY_CMD(0) + 29)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_BACK\fP   (BRLAPI_KEY_CMD(0) + 30)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_RETURN\fP   (BRLAPI_KEY_CMD(0) + 31)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_FREEZE\fP   (BRLAPI_KEY_CMD(0) + 32)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_DISPMD\fP   (BRLAPI_KEY_CMD(0) + 33)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SIXDOTS\fP   (BRLAPI_KEY_CMD(0) + 34)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SLIDEWIN\fP   (BRLAPI_KEY_CMD(0) + 35)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SKPIDLNS\fP   (BRLAPI_KEY_CMD(0) + 36)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SKPBLNKWINS\fP   (BRLAPI_KEY_CMD(0) + 37)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRVIS\fP   (BRLAPI_KEY_CMD(0) + 38)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRHIDE\fP   (BRLAPI_KEY_CMD(0) + 39)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRTRK\fP   (BRLAPI_KEY_CMD(0) + 40)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRSIZE\fP   (BRLAPI_KEY_CMD(0) + 41)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRBLINK\fP   (BRLAPI_KEY_CMD(0) + 42)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ATTRVIS\fP   (BRLAPI_KEY_CMD(0) + 43)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ATTRBLINK\fP   (BRLAPI_KEY_CMD(0) + 44)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CAPBLINK\fP   (BRLAPI_KEY_CMD(0) + 45)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_TUNES\fP   (BRLAPI_KEY_CMD(0) + 46)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_AUTOREPEAT\fP   (BRLAPI_KEY_CMD(0) + 47)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_AUTOSPEAK\fP   (BRLAPI_KEY_CMD(0) + 48)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_HELP\fP   (BRLAPI_KEY_CMD(0) + 49)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_INFO\fP   (BRLAPI_KEY_CMD(0) + 50)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_LEARN\fP   (BRLAPI_KEY_CMD(0) + 51)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PREFMENU\fP   (BRLAPI_KEY_CMD(0) + 52)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PREFSAVE\fP   (BRLAPI_KEY_CMD(0) + 53)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PREFLOAD\fP   (BRLAPI_KEY_CMD(0) + 54)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_FIRST_ITEM\fP   (BRLAPI_KEY_CMD(0) + 55)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_LAST_ITEM\fP   (BRLAPI_KEY_CMD(0) + 56)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_PREV_ITEM\fP   (BRLAPI_KEY_CMD(0) + 57)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_NEXT_ITEM\fP   (BRLAPI_KEY_CMD(0) + 58)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_PREV_SETTING\fP   (BRLAPI_KEY_CMD(0) + 59)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_NEXT_SETTING\fP   (BRLAPI_KEY_CMD(0) + 60)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MUTE\fP   (BRLAPI_KEY_CMD(0) + 61)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPKHOME\fP   (BRLAPI_KEY_CMD(0) + 62)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_LINE\fP   (BRLAPI_KEY_CMD(0) + 63)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_ABOVE\fP   (BRLAPI_KEY_CMD(0) + 64)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_BELOW\fP   (BRLAPI_KEY_CMD(0) + 65)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_SLOWER\fP   (BRLAPI_KEY_CMD(0) + 66)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_FASTER\fP   (BRLAPI_KEY_CMD(0) + 67)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_SOFTER\fP   (BRLAPI_KEY_CMD(0) + 68)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SAY_LOUDER\fP   (BRLAPI_KEY_CMD(0) + 69)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SWITCHVT_PREV\fP   (BRLAPI_KEY_CMD(0) + 70)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SWITCHVT_NEXT\fP   (BRLAPI_KEY_CMD(0) + 71)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CSRJMP_VERT\fP   (BRLAPI_KEY_CMD(0) + 72)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PASTE\fP   (BRLAPI_KEY_CMD(0) + 73)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_RESTARTBRL\fP   (BRLAPI_KEY_CMD(0) + 74)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_RESTARTSPEECH\fP   (BRLAPI_KEY_CMD(0) + 75)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_OFFLINE\fP   (BRLAPI_KEY_CMD(0) + 76)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SHIFT\fP   (BRLAPI_KEY_CMD(0) + 77)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_UPPER\fP   (BRLAPI_KEY_CMD(0) + 78)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CONTROL\fP   (BRLAPI_KEY_CMD(0) + 79)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_META\fP   (BRLAPI_KEY_CMD(0) + 80)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_TIME\fP   (BRLAPI_KEY_CMD(0) + 81)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_MENU_PREV_LEVEL\fP   (BRLAPI_KEY_CMD(0) + 82)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_SEL_LINE\fP   (BRLAPI_KEY_CMD(0) + 83)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_SEL_CHAR\fP   (BRLAPI_KEY_CMD(0) + 84)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_INS_CHARS\fP   (BRLAPI_KEY_CMD(0) + 85)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_DEL_CHARS\fP   (BRLAPI_KEY_CMD(0) + 86)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_REP_CHARS\fP   (BRLAPI_KEY_CMD(0) + 87)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ASPK_CMP_WORDS\fP   (BRLAPI_KEY_CMD(0) + 88)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_CURR_CHAR\fP   (BRLAPI_KEY_CMD(0) + 89)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_PREV_CHAR\fP   (BRLAPI_KEY_CMD(0) + 90)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_NEXT_CHAR\fP   (BRLAPI_KEY_CMD(0) + 91)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_CURR_WORD\fP   (BRLAPI_KEY_CMD(0) + 92)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_PREV_WORD\fP   (BRLAPI_KEY_CMD(0) + 93)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_NEXT_WORD\fP   (BRLAPI_KEY_CMD(0) + 94)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_CURR_LINE\fP   (BRLAPI_KEY_CMD(0) + 95)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_PREV_LINE\fP   (BRLAPI_KEY_CMD(0) + 96)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_NEXT_LINE\fP   (BRLAPI_KEY_CMD(0) + 97)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_FRST_CHAR\fP   (BRLAPI_KEY_CMD(0) + 98)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_LAST_CHAR\fP   (BRLAPI_KEY_CMD(0) + 99)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_FRST_LINE\fP   (BRLAPI_KEY_CMD(0) + 100)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_LAST_LINE\fP   (BRLAPI_KEY_CMD(0) + 101)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_DESC_CURR_CHAR\fP   (BRLAPI_KEY_CMD(0) + 102)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPELL_CURR_WORD\fP   (BRLAPI_KEY_CMD(0) + 103)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ROUTE_CURR_LOCN\fP   (BRLAPI_KEY_CMD(0) + 104)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SPEAK_CURR_LOCN\fP   (BRLAPI_KEY_CMD(0) + 105)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SHOW_CURR_LOCN\fP   (BRLAPI_KEY_CMD(0) + 106)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_TOGGLE_ON\fP   BRLAPI_KEY_FLG(0X0100)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_TOGGLE_OFF\fP   BRLAPI_KEY_FLG(0X0200)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_TOGGLE_MASK\fP   (BRLAPI_KEY_FLG_TOGGLE_ON | BRLAPI_KEY_FLG_TOGGLE_OFF)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_MOTION_ROUTE\fP   BRLAPI_KEY_FLG(0X0400)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_REPEAT_INITIAL\fP   BRLAPI_KEY_FLG(0X8000)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_REPEAT_DELAY\fP   BRLAPI_KEY_FLG(0X4000)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_REPEAT_MASK\fP   (BRLAPI_KEY_FLG_REPEAT_INITIAL | BRLAPI_KEY_FLG_REPEAT_DELAY)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_ROUTE\fP   BRLAPI_KEY_CMD(0X01)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CLIP_NEW\fP   BRLAPI_KEY_CMD(0X02)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CUTBEGIN\fP   BRLAPI_KEY_CMD(0X02)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CLIP_ADD\fP   BRLAPI_KEY_CMD(0X03)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CUTAPPEND\fP   BRLAPI_KEY_CMD(0X03)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_COPY_RECT\fP   BRLAPI_KEY_CMD(0X04)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CUTRECT\fP   BRLAPI_KEY_CMD(0X04)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_COPY_LINE\fP   BRLAPI_KEY_CMD(0X05)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CUTLINE\fP   BRLAPI_KEY_CMD(0X05)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SWITCHVT\fP   BRLAPI_KEY_CMD(0X06)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRINDENT\fP   BRLAPI_KEY_CMD(0X07)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXINDENT\fP   BRLAPI_KEY_CMD(0X08)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_DESCCHAR\fP   BRLAPI_KEY_CMD(0X09)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SETLEFT\fP   BRLAPI_KEY_CMD(0X0A)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_SETMARK\fP   BRLAPI_KEY_CMD(0X0B)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_GOTOMARK\fP   BRLAPI_KEY_CMD(0X0C)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_GOTOLINE\fP   BRLAPI_KEY_CMD(0X0D)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_LINE_SCALED\fP   BRLAPI_KEY_FLG(0X0100)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_LINE_TOLEFT\fP   BRLAPI_KEY_FLG(0X0200)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PRDIFCHAR\fP   BRLAPI_KEY_CMD(0X0E)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_NXDIFCHAR\fP   BRLAPI_KEY_CMD(0X0F)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CLIP_COPY\fP   BRLAPI_KEY_CMD(0X10)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_COPYCHARS\fP   BRLAPI_KEY_CMD(0X10)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CLIP_APPEND\fP   BRLAPI_KEY_CMD(0X11)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_APNDCHARS\fP   BRLAPI_KEY_CMD(0X11)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PWGEN\fP   BRLAPI_KEY_CMD(0X12)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PASSDOTS\fP   BRLAPI_KEY_CMD(0X22)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_SHIFT\fP   BRLAPI_KEY_FLG(0X01)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_UPPER\fP   BRLAPI_KEY_FLG(0X02)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_CONTROL\fP   BRLAPI_KEY_FLG(0X04)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_META\fP   BRLAPI_KEY_FLG(0X08)"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT1\fP   0001"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT2\fP   0002"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT3\fP   0004"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT4\fP   0010"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT5\fP   0020"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT6\fP   0040"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT7\fP   0100"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT8\fP   0200"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOTC\fP   0400"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PASSAT\fP   BRLAPI_KEY_CMD(0X23)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PASSXT\fP   BRLAPI_KEY_CMD(0X24)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_PASSPS2\fP   BRLAPI_KEY_CMD(0X25)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_KBD_RELEASE\fP   BRLAPI_KEY_FLG(0X0100)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_KBD_EMUL0\fP   BRLAPI_KEY_FLG(0X0200)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_FLG_KBD_EMUL1\fP   BRLAPI_KEY_FLG(0X0400)"
.br
.ti -1c
.RI "#define \fBBRLAPI_KEY_CMD_CONTEXT\fP   BRLAPI_KEY_CMD(0X26)"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOTS\fP(dot1, dot2, dot3, dot4, dot5, dot6, dot7, dot8)"
.br
.ti -1c
.RI "#define \fBBRLAPI_DOT_CHORD\fP   256"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
