.TH "brlapi_writeArgumentsPacket_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_writeArgumentsPacket_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of extended write packets 
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBbrlapi_writeArgumentsPacket_t::data\fP"Flags to tell which fields are present 
.SS "uint32_t \fBbrlapi_writeArgumentsPacket_t::flags\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
