.TH "brlapi_authServerPacket_t" 3 "Thu Jun 7 2012" "Version 1.0" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_authServerPacket_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi_protocol.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBbrlapi_authServerPacket_t::type\fP[1]"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code.
