# Dependencies for braille.$O:
braille.$O: $(SRC_DIR)/braille.c
braille.$O: $(BLD_TOP)config.h
braille.$O: $(BLD_TOP)forbuild.h
braille.$O: $(SRC_TOP)prologue.h
braille.$O: $(SRC_TOP)Programs/log.h
braille.$O: $(SRC_TOP)Programs/brl.h
braille.$O: $(BLD_TOP)Programs/brlapi_constants.h
braille.$O: $(SRC_TOP)Programs/brlapi_keycodes.h
braille.$O: $(SRC_TOP)Programs/brldefs.h
braille.$O: $(SRC_TOP)Programs/brltty.h
braille.$O: $(SRC_TOP)Programs/cmd.h
braille.$O: $(SRC_TOP)Programs/ctb.h
braille.$O: $(SRC_TOP)Programs/ctbdefs.h
braille.$O: $(SRC_TOP)Programs/driver.h
braille.$O: $(SRC_TOP)Programs/io_generic.h
braille.$O: $(SRC_TOP)Programs/ktb.h
braille.$O: $(SRC_TOP)Programs/ktbdefs.h
braille.$O: $(SRC_TOP)Programs/menu.h
braille.$O: $(SRC_TOP)Programs/pid.h
braille.$O: $(SRC_TOP)Programs/prefs.h
braille.$O: $(SRC_TOP)Programs/program.h
braille.$O: $(SRC_TOP)Programs/scr.h
braille.$O: $(SRC_TOP)Programs/serialdefs.h
braille.$O: $(SRC_TOP)Programs/ses.h
braille.$O: $(SRC_TOP)Programs/spk.h
braille.$O: $(SRC_TOP)Programs/spkdefs.h
braille.$O: $(SRC_TOP)Programs/timing.h
braille.$O: $(SRC_TOP)Programs/usbdefs.h
braille.$O: $(SRC_TOP)Programs/brl_driver.h
braille.$O: $(SRC_TOP)Programs/statdefs.h

